# =============================================================
#  credentials.py  -  Auto-generated by setup.py
#  Run setup.py again to reconfigure.
# =============================================================

DB_TYPE = "sqlite"

# SQLite path (this PC)
SQLITE_PATH = r"C:\Users\HP\Desktop\sessions_monitor\sessions.db"

# MySQL (not used unless you change DB_TYPE)
MYSQL_HOST     = "192.168.1.105"
MYSQL_PORT     = 3306
MYSQL_DB       = "sessions"
MYSQL_USER     = "admin"
MYSQL_PASSWORD = ""

# PostgreSQL (not used unless you change DB_TYPE)
PG_HOST        = "192.168.1.105"
PG_PORT        = 5432
PG_DB          = "sessions"
PG_USER        = "admin"
PG_PASSWORD    = ""

# Folder to watch
SESSIONS_FOLDER = r"\\192.168.1.105\sessions"

# Behaviour
POLL_INTERVAL = 5
DEFAULT_SITE  = ""
