# =============================================================
#  credentials.py  -  Auto-generated by setup.py
#  Run setup.py again to reconfigure.
# =============================================================

# ODBC Configuration
ODBC_DRIVER = "ODBC Driver 17 for SQL Server"  # or your ODBC driver name
ODBC_SERVER = "192.168.1.105"
ODBC_DATABASE = "sessions"
ODBC_USER = "admin"
ODBC_PASSWORD = ""
ODBC_TRUSTED_CONNECTION = False  # Set to True for Windows Authentication

# Folder to watch
SESSIONS_FOLDER = r"\\192.168.1.105\sessions"

# Behaviour
POLL_INTERVAL = 5
DEFAULT_SITE = ""
