# -*- coding: utf-8 -*-
"""
setup.py  -  First time setup wizard for pyodbc configuration.
Run this ONCE on any PC before starting the monitor.
Configures ODBC connection details and network share access.

Usage:
    python setup.py
"""

import os
import sys
import subprocess
import pyodbc


# ─── Colours ─────────────────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
CYAN   = "\033[96m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
WHITE  = "\033[97m"

def c(colour, text):
    return f"{colour}{text}{RESET}"

def clear():
    os.system("cls" if os.name == "nt" else "clear")

def ask(prompt, default=None):
    """Ask a question. If user presses Enter, return default."""
    if default:
        display = f"  {c(CYAN, '?')} {prompt}\n    {c(DIM, f'[Enter] = {default}')}\n  {c(CYAN,'>')} "
    else:
        display = f"  {c(CYAN, '?')} {prompt}\n  {c(CYAN,'>')} "
    val = input(display).strip()
    print()
    return val if val else default

def success(msg):
    print(f"  {c(GREEN, '✔')}  {msg}")

def warn(msg):
    print(f"  {c(YELLOW, '!')}  {msg}")

def error(msg):
    print(f"  {c(RED, '✘')}  {msg}")

def info(msg):
    print(f"  {c(DIM, '·')}  {msg}")


# ─── Banner ───────────────────────────────────────────────────────────────────

def banner():
    clear()
    print()
    print(c(CYAN, "  ╔══════════════════════════════════════════════╗"))
    print(c(CYAN, "  ║") + c(BOLD + WHITE, "    SESSION MONITOR - ODBC Setup             ") + c(CYAN, "║"))
    print(c(CYAN, "  ║") + c(DIM,          "    Configure your database connection       ") + c(CYAN, "║"))
    print(c(CYAN, "  ╚══════════════════════════════════════════════╝"))
    print()


# ─── ODBC driver detection ────────────────────────────────────────────────────

def get_installed_drivers():
    """Return list of installed ODBC drivers."""
    try:
        return sorted(pyodbc.drivers())
    except Exception:
        return []

def get_default_driver():
    """Try to find the most common SQL Server driver."""
    drivers = get_installed_drivers()
    for preferred in ["ODBC Driver 17 for SQL Server", "ODBC Driver 18 for SQL Server", "SQL Server"]:
        if preferred in drivers:
            return preferred
    return drivers[0] if drivers else None


# ─── Validation helpers ───────────────────────────────────────────────────────

def validate_ip(ip):
    parts = ip.split(".")
    if len(parts) != 4:
        return False
    try:
        return all(0 <= int(p) <= 255 for p in parts)
    except ValueError:
        return False

def test_odbc_connection(driver, server, database, user, password, trusted):
    """Test ODBC connection with given parameters."""
    try:
        if trusted:
            conn_str = (
                f"Driver={{{driver}}};"
                f"Server={server};"
                f"Database={database};"
                f"Trusted_Connection=yes;"
            )
        else:
            conn_str = (
                f"Driver={{{driver}}};"
                f"Server={server};"
                f"Database={database};"
                f"UID={user};"
                f"PWD={password};"
            )
        conn = pyodbc.connect(conn_str, timeout=5)
        conn.close()
        return True, "Connection successful"
    except Exception as e:
        return False, str(e)

def test_share_access(path):
    """Return True if we can access the network share."""
    try:
        return os.path.exists(path)
    except Exception:
        return False

def try_net_use(ip, username, password):
    """Attempt to mount the share using net use."""
    share = f"\\\\{ip}\\sessions"
    try:
        # disconnect first
        subprocess.run(
            ["net", "use", share, "/delete", "/y"],
            capture_output=True, timeout=10
        )
    except Exception:
        pass
    cmd = ["net", "use", share]
    if password:
        cmd.append(password)
    if username:
        cmd.append(f"/user:{username}")
    cmd.append("/persistent:yes")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        return result.returncode == 0, result.stderr.strip() or result.stdout.strip()
    except Exception as e:
        return False, str(e)


# ─── Write credentials.py ────────────────────────────────────────────────────

def write_credentials(config: dict):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path   = os.path.join(script_dir, "credentials.py")

    lines = f'''\
# =============================================================
#  credentials.py  -  Auto-generated by setup.py
#  Run setup.py again to reconfigure.
# =============================================================

# ODBC Configuration
ODBC_DRIVER = "{config['odbc_driver']}"
ODBC_SERVER = "{config['server']}"
ODBC_DATABASE = "{config['database']}"
ODBC_USER = "{config['user']}"
ODBC_PASSWORD = "{config['password']}"
ODBC_TRUSTED_CONNECTION = {str(config['trusted']).lower()}

# Folder to watch
SESSIONS_FOLDER = r"\\\\{config['server_ip']}\\sessions"

# Behaviour
POLL_INTERVAL = {config.get('poll_interval', 5)}
DEFAULT_SITE = ""
'''
    with open(out_path, "w") as f:
        f.write(lines)
    return out_path


# ─── Create DB ─────────────────────────────────────────────────────────────

def create_database():
    """Import db (which reads the freshly written credentials.py) and init."""
    # Force reimport so new credentials.py is picked up
    if "credentials" in sys.modules:
        del sys.modules["credentials"]
    if "db" in sys.modules:
        del sys.modules["db"]

    import db as database
    database.init_db()


# ─── Main wizard ─────────────────────────────────────────────────────────────

def run():
    banner()

    # ── Section 0: ODBC Driver selection ─────────────────────
    print(c(BOLD, "  0 · ODBC Driver"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    drivers = get_installed_drivers()
    if not drivers:
        error("No ODBC drivers found on this system.")
        error("Please install an ODBC driver (e.g., 'ODBC Driver 17 for SQL Server')")
        sys.exit(1)

    info(f"Found {len(drivers)} ODBC driver(s):")
    for i, driver in enumerate(drivers, 1):
        print(f"    {i}. {driver}")
    print()

    default_driver = get_default_driver()
    driver_choice = ask(
        f"Select ODBC driver (number or name)",
        default=default_driver or drivers[0]
    )

    # Resolve driver selection
    if driver_choice.isdigit():
        idx = int(driver_choice) - 1
        if 0 <= idx < len(drivers):
            selected_driver = drivers[idx]
        else:
            error(f"Invalid selection: {driver_choice}")
            sys.exit(1)
    elif driver_choice in drivers:
        selected_driver = driver_choice
    else:
        error(f"Driver not found: {driver_choice}")
        sys.exit(1)

    success(f"Selected: {selected_driver}")
    print()

    # ── Section 1: Server details ────────────────────────────
    print(c(BOLD, "  1 · Server details"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    while True:
        server = ask("SQL Server address (e.g., 192.168.1.105 or localhost)", default="localhost")
        if not server:
            error("Server address is required.")
            continue
        break

    while True:
        database = ask("Database name", default="sessions")
        if not database:
            error("Database name is required.")
            continue
        break

    print()

    # ── Section 2: Authentication ───────────────────────────
    print(c(BOLD, "  2 · Authentication"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    auth_choice = ask(
        "Use Windows Authentication (Trusted Connection)? (y/n)",
        default="y"
    ).lower()
    use_trusted = auth_choice in ["y", "yes", "true"]

    if use_trusted:
        user = ""
        password = ""
        info("Will use Windows Authentication")
    else:
        user = ask("SQL Server username", default="admin")
        password = ask("SQL Server password (or press Enter to skip)", default="")

    print()

    # ── Section 3: Test connection ───────────────────────────
    print(c(BOLD, "  3 · Test connection"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    info("Testing ODBC connection...")
    ok, msg = test_odbc_connection(selected_driver, server, database, user, password, use_trusted)
    if ok:
        success("Connection successful!")
    else:
        warn(f"Connection failed: {msg}")
        proceed = ask("Continue anyway? (y/n)", default="y").lower()
        if proceed not in ["y", "yes"]:
            sys.exit(1)

    print()

    # ── Section 4: Network share ─────────────────────────────
    print(c(BOLD, "  4 · Network share access"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    server_ip = ask("Server IP for sessions folder", default="192.168.1.105")
    share_path = f"\\\\{server_ip}\\sessions"
    info(f"Will watch: {share_path}")
    print()

    if test_share_access(share_path):
        success(f"Share is accessible")
        share_user = None
        share_password = None
    else:
        warn("Cannot access share yet. Enter credentials to connect.")
        print()
        share_user = ask("Username (or press Enter to skip)", default=None)
        share_password = ask("Password (or press Enter to skip)", default=None)

        if share_user or share_password:
            info("Connecting to share...")
            ok, msg = try_net_use(server_ip, share_user, share_password)
            if ok:
                success("Connected to share successfully.")
            else:
                warn(f"Could not connect automatically: {msg}")
                warn("The monitor may still work if the share is accessible manually.")
        else:
            warn("No credentials provided - make sure the share is accessible manually.")

    print()

    # ── Section 5: Poll interval ─────────────────────────────
    print(c(BOLD, "  5 · Scan frequency"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    while True:
        poll = ask("How often should the monitor scan? (seconds)", default="5")
        try:
            poll = int(poll)
            if poll < 1:
                raise ValueError
            break
        except ValueError:
            error("Please enter a number (e.g. 5)")

    # ── Write credentials.py ─────────────────────────────────
    print(c(BOLD, "  6 · Writing configuration"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    config = {
        "odbc_driver":   selected_driver,
        "server":        server,
        "database":      database,
        "user":          user,
        "password":      password,
        "trusted":       use_trusted,
        "server_ip":     server_ip,
        "poll_interval": poll,
    }

    try:
        creds_path = write_credentials(config)
        success(f"credentials.py written")
        info(f"  → {creds_path}")
    except Exception as e:
        error(f"Could not write credentials.py: {e}")
        sys.exit(1)

    # ── Create DB ────────────────────────────────────────────
    try:
        create_database()
        success(f"Database tables created")
    except Exception as e:
        error(f"Could not create database: {e}")
        sys.exit(1)

    # ── Done ─────────────────────────────────────────────────
    print()
    print(c(CYAN, "  ╔══════════════════════════════════════════════╗"))
    print(c(CYAN, "  ║") + c(GREEN + BOLD, "    ✔  Setup complete!                       ") + c(CYAN, "║"))
    print(c(CYAN, "  ╠══════════════════════════════════════════════╣"))
    print(c(CYAN, "  ║") + f"    Driver  : {c(WHITE, selected_driver[:41]):<41}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Server  : {c(WHITE, server[:51]):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Database: {c(WHITE, database[:51]):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Watching: {c(WHITE, share_path[:51]):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Polling : {c(WHITE, f'every {poll}s'):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ╠══════════════════════════════════════════════╣"))
    print(c(CYAN, "  ║") + c(DIM, "    Now run:  python monitor.py              ") + c(CYAN, "║"))
    print(c(CYAN, "  ╚══════════════════════════════════════════════╝"))
    print()


if __name__ == "__main__":
    run()
