# -*- coding: utf-8 -*-
"""
setup.py  -  First time setup wizard.
Run this ONCE on any PC before starting the monitor.
It figures out all paths automatically and writes credentials.py for you.

Usage:
    python setup.py
"""

import os
import sys
import subprocess
import pyodbc


# ─── Colours ─────────────────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
CYAN   = "\033[96m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
WHITE  = "\033[97m"

def c(colour, text):
    return f"{colour}{text}{RESET}"

def clear():
    os.system("cls" if os.name == "nt" else "clear")

def ask(prompt, default=None):
    """Ask a question. If user presses Enter, return default."""
    if default:
        display = f"  {c(CYAN, '?')} {prompt}\n    {c(DIM, f'[Enter] = {default}')}\n  {c(CYAN,'>')} "
    else:
        display = f"  {c(CYAN, '?')} {prompt}\n  {c(CYAN,'>')} "
    val = input(display).strip()
    print()
    return val if val else default

def ask_yes_no(prompt, default="n"):
    """Ask a yes/no question."""
    display = f"  {c(CYAN, '?')} {prompt} ({default.lower()}/{'n' if default.lower() == 'y' else 'y'}) "
    val = input(display).strip().lower()
    print()
    return val in ("y", "yes") if val else default.lower() in ("y", "yes")

def success(msg):
    print(f"  {c(GREEN, '✔')}  {msg}")

def warn(msg):
    print(f"  {c(YELLOW, '!')}  {msg}")

def error(msg):
    print(f"  {c(RED, '✘')}  {msg}")

def info(msg):
    print(f"  {c(DIM, '·')}  {msg}")


# ─── Banner ───────────────────────────────────────────────────────────────────

def banner():
    clear()
    print()
    print(c(CYAN, "  ╔══════════════════════════════════════════════╗"))
    print(c(CYAN, "  ║") + c(BOLD + WHITE, "    SESSION MONITOR - First Time Setup      ") + c(CYAN, "║"))
    print(c(CYAN, "  ║") + c(DIM,          "    Run this once on every new PC           ") + c(CYAN, "║"))
    print(c(CYAN, "  ╚══════════════════════════════════════════════╝"))
    print()


# ─── Auto-detect ODBC drivers ─────────────────────────────────────────────────

def get_available_drivers():
    """Get list of available ODBC drivers on the system."""
    try:
        drivers = pyodbc.drivers()
        return [d for d in drivers if 'SQL Server' in d or 'ODBC Driver' in d]
    except Exception:
        return []

def get_default_server():
    """Try to guess the server from existing credentials.py if present."""
    try:
        import credentials as cfg
        return cfg.ODBC_SERVER if hasattr(cfg, 'ODBC_SERVER') else None
    except Exception:
        return None


# ─── Validation helpers ───────────────────────────────────────────────────────

def test_share_access(path):
    """Return True if we can list the network share."""
    try:
        return os.path.exists(path)
    except Exception:
        return False

def try_net_use(ip, username, password):
    """Attempt to mount the share using net use."""
    share = f"\\\\{ip}\\sessions"
    try:
        # disconnect first
        subprocess.run(
            ["net", "use", share, "/delete", "/y"],
            capture_output=True, timeout=10
        )
    except Exception:
        pass
    cmd = ["net", "use", share]
    if password:
        cmd.append(password)
    if username:
        cmd.append(f"/user:{username}")
    cmd.append("/persistent:yes")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        return result.returncode == 0, result.stderr.strip() or result.stdout.strip()
    except Exception as e:
        return False, str(e)

def test_odbc_connection(driver, server, database, user, password, trusted):
    """Test ODBC connection."""
    try:
        if trusted:
            conn_str = (
                f"Driver={{{driver}}};"
                f"Server={server};"
                f"Database={database};"
                f"Trusted_Connection=yes;"
            )
        else:
            conn_str = (
                f"Driver={{{driver}}};"
                f"Server={server};"
                f"Database={database};"
                f"UID={user};"
                f"PWD={password};"
            )
        conn = pyodbc.connect(conn_str, timeout=10)
        conn.close()
        return True, "Connected successfully"
    except Exception as e:
        return False, str(e)


# ─── Write credentials.py ────────────────────────────────────────────────────

def write_credentials(config: dict):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path   = os.path.join(script_dir, "credentials.py")

    lines = f'''\
# =============================================================
#  credentials.py  -  Auto-generated by setup.py
#  Run setup.py again to reconfigure.
# =============================================================

# ODBC Configuration
ODBC_DRIVER = "{config['odbc_driver']}"
ODBC_SERVER = "{config['server']}"
ODBC_DATABASE = "{config['database']}"
ODBC_USER = "{config['user']}"
ODBC_PASSWORD = "{config['password']}"
ODBC_TRUSTED_CONNECTION = {str(config['trusted']).lower()}

# Folder to watch
SESSIONS_FOLDER = r"\\\\{config['server']}\\sessions"

# Behaviour
POLL_INTERVAL = {config.get('poll_interval', 5)}
DEFAULT_SITE = ""
'''
    with open(out_path, "w") as f:
        f.write(lines)
    return out_path


# ─── Create DB ─────────────────────────────────────────────────────────────────

def create_database():
    """Import db (which reads the freshly written credentials.py) and init."""
    # Force reimport so new credentials.py is picked up
    if "credentials" in sys.modules:
        del sys.modules["credentials"]
    if "db" in sys.modules:
        del sys.modules["db"]

    import db as database
    database.init_db()


# ─── Main wizard ───────────────────────────────────────────────────────────────

def run():
    banner()

    # ── Section 1: ODBC Driver ──────────────────────────────
    print(c(BOLD, "  1 · ODBC Driver"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    available_drivers = get_available_drivers()
    
    if not available_drivers:
        error("No SQL Server ODBC drivers found on this system.")
        error("Please install 'ODBC Driver 17 for SQL Server' or similar.")
        sys.exit(1)

    info("Available ODBC drivers:")
    for i, driver in enumerate(available_drivers, 1):
        print(f"    {i}. {driver}")
    print()

    while True:
        choice = ask(f"Select driver (1-{len(available_drivers)})", default="1")
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(available_drivers):
                odbc_driver = available_drivers[idx]
                break
            else:
                error(f"Please enter a number between 1 and {len(available_drivers)}")
        except ValueError:
            error("Please enter a valid number")

    print()

    # ── Section 2: Server details ────────────────────────
    print(c(BOLD, "  2 · Server details"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    while True:
        server = ask("SQL Server address (IP or hostname)", default=get_default_server())
        if not server:
            error("Server address is required.")
            continue
        break

    database = ask("Database name", default="sessions")
    print()

    # ── Section 3: Authentication ───────────────────────
    print(c(BOLD, "  3 · Authentication"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    auth_type = ask("Use Windows Authentication? (y/n)", default="y")
    trusted_connection = auth_type.lower() in ("y", "yes")
    
    if trusted_connection:
        info("Using Windows Authentication (Trusted Connection)")
        db_user = ""
        db_password = ""
    else:
        db_user = ask("Database username", default="sa")
        db_password = ask("Database password", default="")
    
    print()

    # ── Section 4: Test connection ───────────────────────
    print(c(BOLD, "  4 · Test connection"))
    print(c(DIM,  "  " + "─" * 44))
    print()
    
    info("Testing ODBC connection...")
    ok, msg = test_odbc_connection(odbc_driver, server, database, db_user, db_password, trusted_connection)
    
    if ok:
        success("ODBC connection successful!")
    else:
        warn(f"Connection failed: {msg}")
        if not ask_yes_no("Continue anyway?", default="n"):
            info("Setup cancelled.")
            sys.exit(0)
    
    print()

    # ── Section 5: Network share access ──────────────────
    print(c(BOLD, "  5 · Network share access"))
    print(c(DIM,  "  " + "─" * 44))
    print()
    info("Testing access to the share...")
    print()

    share_path = f"\\\\{server}\\sessions"
    
    if test_share_access(share_path):
        success(f"Share is accessible - no credentials needed.")
        print()
        share_username = None
        share_password = None
    else:
        warn("Cannot access share yet. Enter credentials to connect.")
        print()
        share_username = ask("Username (or press Enter to skip)", default=None)
        share_password = ask("Password (or press Enter to skip)", default=None)

        if share_username or share_password:
            info("Connecting to share...")
            ok, msg = try_net_use(server, share_username, share_password)
            if ok:
                success("Connected to share successfully.")
            else:
                warn(f"Could not connect automatically: {msg}")
                warn("The monitor may still work if the share is accessible.")
            print()
        else:
            warn("No credentials provided - make sure the share is accessible manually.")
            print()

    # ── Section 6: Poll interval ─────────────────────────
    print(c(BOLD, "  6 · Scan frequency"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    while True:
        poll = ask("How often should the monitor scan? (seconds)", default="5")
        try:
            poll = int(poll)
            if poll < 1:
                raise ValueError
            break
        except ValueError:
            error("Please enter a number (e.g. 5)")

    # ── Write credentials.py ─────────────────────────────────
    print(c(BOLD, "  7 · Writing configuration"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    config = {
        "odbc_driver":  odbc_driver,
        "server":       server,
        "database":     database,
        "user":         db_user,
        "password":     db_password,
        "trusted":      trusted_connection,
        "poll_interval": poll,
    }

    try:
        creds_path = write_credentials(config)
        success(f"credentials.py written")
        info(f"  → {creds_path}")
    except Exception as e:
        error(f"Could not write credentials.py: {e}")
        sys.exit(1)

    # ── Create DB ────────────────────────────────────────────
    try:
        create_database()
        success(f"Database initialized")
    except Exception as e:
        error(f"Could not initialize database: {e}")
        sys.exit(1)

    # ── Done ─────────────────────────────────────────────────
    print()
    print(c(CYAN, "  ╔══════════════════════════════════════════════╗"))
    print(c(CYAN, "  ║") + c(GREEN + BOLD, "    ✔  Setup complete!                       ") + c(CYAN, "║"))
    print(c(CYAN, "  ╠══════════════════════════════════════════════╣"))
    print(c(CYAN, "  ║") + f"    Driver  : {c(WHITE, odbc_driver):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Server  : {c(WHITE, server):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Database: {c(WHITE, database):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Watching: {c(WHITE, share_path):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Polling : {c(WHITE, f'every {poll}s'):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ╠══════════════════════════════════════════════╣"))
    print(c(CYAN, "  ║") + c(DIM, "    Now run:  python monitor.py              ") + c(CYAN, "║"))
    print(c(CYAN, "  ╚══════════════════════════════════════════════╝"))
    print()


if __name__ == "__main__":
    run()
