# -*- coding: utf-8 -*-
"""
setup.py  -  First time setup wizard.
Run this ONCE on any PC before starting the monitor.
It figures out all paths automatically and writes credentials.py for you.

Usage:
    python setup.py
"""

import os
import sys
import subprocess


# ─── Colours ─────────────────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
CYAN   = "\033[96m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
WHITE  = "\033[97m"

def c(colour, text):
    return f"{colour}{text}{RESET}"

def clear():
    os.system("cls" if os.name == "nt" else "clear")

def ask(prompt, default=None):
    """Ask a question. If user presses Enter, return default."""
    if default:
        display = f"  {c(CYAN, '?')} {prompt}\n    {c(DIM, f'[Enter] = {default}')}\n  {c(CYAN,'>')} "
    else:
        display = f"  {c(CYAN, '?')} {prompt}\n  {c(CYAN,'>')} "
    val = input(display).strip()
    print()
    return val if val else default

def success(msg):
    print(f"  {c(GREEN, '✔')}  {msg}")

def warn(msg):
    print(f"  {c(YELLOW, '!')}  {msg}")

def error(msg):
    print(f"  {c(RED, '✘')}  {msg}")

def info(msg):
    print(f"  {c(DIM, '·')}  {msg}")


# ─── Banner ───────────────────────────────────────────────────────────────────

def banner():
    clear()
    print()
    print(c(CYAN, "  ╔══════════════════════════════════════════════╗"))
    print(c(CYAN, "  ║") + c(BOLD + WHITE, "    SESSION MONITOR - First Time Setup      ") + c(CYAN, "║"))
    print(c(CYAN, "  ║") + c(DIM,          "    Run this once on every new PC           ") + c(CYAN, "║"))
    print(c(CYAN, "  ╚══════════════════════════════════════════════╝"))
    print()


# ─── Auto-detect defaults ────────────────────────────────────────────────────

def get_default_db_path():
    """Put sessions.db in the same folder as this script."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(script_dir, "sessions.db")

def get_default_ip():
    """Try to guess the server IP from existing credentials.py if present."""
    try:
        import credentials as cfg
        return cfg.MYSQL_HOST if cfg.DB_TYPE == "mysql" else None
    except Exception:
        return None


# ─── Validation helpers ───────────────────────────────────────────────────────

def validate_ip(ip):
    parts = ip.split(".")
    if len(parts) != 4:
        return False
    try:
        return all(0 <= int(p) <= 255 for p in parts)
    except ValueError:
        return False

def test_share_access(path):
    """Return True if we can list the network share."""
    try:
        return os.path.exists(path)
    except Exception:
        return False

def try_net_use(ip, username, password):
    """Attempt to mount the share using net use."""
    share = f"\\\\{ip}\\sessions"
    try:
        # disconnect first
        subprocess.run(
            ["net", "use", share, "/delete", "/y"],
            capture_output=True, timeout=10
        )
    except Exception:
        pass
    cmd = ["net", "use", share]
    if password:
        cmd.append(password)
    if username:
        cmd.append(f"/user:{username}")
    cmd.append("/persistent:yes")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        return result.returncode == 0, result.stderr.strip() or result.stdout.strip()
    except Exception as e:
        return False, str(e)


# ─── Write credentials.py ────────────────────────────────────────────────────

def write_credentials(config: dict):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path   = os.path.join(script_dir, "credentials.py")

    lines = f'''\
# =============================================================
#  credentials.py  -  Auto-generated by setup.py
#  Run setup.py again to reconfigure.
# =============================================================

DB_TYPE = "sqlite"

# SQLite path (this PC)
SQLITE_PATH = r"{config['sqlite_path']}"

# MySQL (not used unless you change DB_TYPE)
MYSQL_HOST     = "{config.get('server_ip', '192.168.1.100')}"
MYSQL_PORT     = 3306
MYSQL_DB       = "sessions"
MYSQL_USER     = "{config.get('db_user', 'admin')}"
MYSQL_PASSWORD = "{config.get('db_password', '')}"

# PostgreSQL (not used unless you change DB_TYPE)
PG_HOST        = "{config.get('server_ip', '192.168.1.100')}"
PG_PORT        = 5432
PG_DB          = "sessions"
PG_USER        = "admin"
PG_PASSWORD    = ""

# Folder to watch
SESSIONS_FOLDER = r"\\\\{config['server_ip']}\\sessions"

# Behaviour
POLL_INTERVAL = {config.get('poll_interval', 5)}
DEFAULT_SITE  = ""
'''
    with open(out_path, "w") as f:
        f.write(lines)
    return out_path


# ─── Create DB ───────────────────────────────────────────────────────────────

def create_database():
    """Import db (which reads the freshly written credentials.py) and init."""
    # Force reimport so new credentials.py is picked up
    if "credentials" in sys.modules:
        del sys.modules["credentials"]
    if "db" in sys.modules:
        del sys.modules["db"]

    import db as database
    database.init_db()


# ─── Main wizard ─────────────────────────────────────────────────────────────

def run():
    banner()

    # ── Section 1: Server IP ────────────────────────────────
    print(c(BOLD, "  1 · Server details"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    while True:
        ip = ask("What is the server IP address?", default=get_default_ip())
        if not ip:
            error("IP address is required.")
            continue
        if not validate_ip(ip):
            error(f"'{ip}' doesn't look like a valid IP. Example: 192.168.1.105")
            continue
        break

    share_path = f"\\\\{ip}\\sessions"
    info(f"Will watch: {share_path}")
    print()

    # ── Section 2: Share credentials ────────────────────────
    print(c(BOLD, "  2 · Network share access"))
    print(c(DIM,  "  " + "─" * 44))
    print()
    info("Testing access to the share...")
    print()

    if test_share_access(share_path):
        success(f"Share is accessible - no credentials needed.")
        print()
        username = None
        password = None
    else:
        warn("Cannot access share yet. Enter credentials to connect.")
        print()
        username = ask("Username (or press Enter to skip)", default=None)
        password = ask("Password (or press Enter to skip)", default=None)

        if username or password:
            info("Connecting to share...")
            ok, msg = try_net_use(ip, username, password)
            if ok:
                success("Connected to share successfully.")
            else:
                warn(f"Could not connect automatically: {msg}")
                warn("The monitor may still work if the share is accessible.")
            print()
        else:
            warn("No credentials provided - make sure the share is accessible manually.")
            print()

    # ── Section 3: Database path ─────────────────────────────
    print(c(BOLD, "  3 · Database location on this PC"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    default_db = get_default_db_path()
    db_path    = ask("Where should sessions.db be saved?", default=default_db)

    # Make sure parent folder exists
    parent = os.path.dirname(os.path.abspath(db_path))
    if not os.path.exists(parent):
        try:
            os.makedirs(parent, exist_ok=True)
            info(f"Created folder: {parent}")
        except Exception as e:
            error(f"Could not create folder: {e}")
            sys.exit(1)

    # ── Section 4: Poll interval ─────────────────────────────
    print(c(BOLD, "  4 · Scan frequency"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    while True:
        poll = ask("How often should the monitor scan? (seconds)", default="5")
        try:
            poll = int(poll)
            if poll < 1:
                raise ValueError
            break
        except ValueError:
            error("Please enter a number (e.g. 5)")

    # ── Write credentials.py ─────────────────────────────────
    print(c(BOLD, "  5 · Writing configuration"))
    print(c(DIM,  "  " + "─" * 44))
    print()

    config = {
        "server_ip":     ip,
        "sqlite_path":   os.path.abspath(db_path),
        "db_user":       username or "admin",
        "db_password":   password or "",
        "poll_interval": poll,
    }

    try:
        creds_path = write_credentials(config)
        success(f"credentials.py written")
        info(f"  → {creds_path}")
    except Exception as e:
        error(f"Could not write credentials.py: {e}")
        sys.exit(1)

    # ── Create DB ────────────────────────────────────────────
    try:
        create_database()
        success(f"Database created")
        info(f"  → {os.path.abspath(db_path)}")
    except Exception as e:
        error(f"Could not create database: {e}")
        sys.exit(1)

    # ── Done ─────────────────────────────────────────────────
    print()
    print(c(CYAN, "  ╔══════════════════════════════════════════════╗"))
    print(c(CYAN, "  ║") + c(GREEN + BOLD, "    ✔  Setup complete!                       ") + c(CYAN, "║"))
    print(c(CYAN, "  ╠══════════════════════════════════════════════╣"))
    print(c(CYAN, "  ║") + f"    Server  : {c(WHITE, ip):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Watching: {c(WHITE, share_path):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Database: {c(WHITE, os.path.basename(db_path)):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ║") + f"    Polling : {c(WHITE, f'every {poll}s'):<51}" + c(CYAN, "║"))
    print(c(CYAN, "  ╠══════════════════════════════════════════════╣"))
    print(c(CYAN, "  ║") + c(DIM, "    Now run:  python monitor.py              ") + c(CYAN, "║"))
    print(c(CYAN, "  ╚══════════════════════════════════════════════╝"))
    print()


if __name__ == "__main__":
    run()